options:
  merge-default-rules: true
rules:
  no-css-comments: 0
  no-color-literals: 0
  no-color-keywords: 0
  property-sort-order: 0
  no-vendor-prefixes: 0
  nesting-depth:
    - 3
  leading-zero:
    - 1
    -
      include: true
  force-attribute-nesting: 0
  no-qualifying-elements: 0
  mixins-before-declarations: 0
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: snakecase
